# SCS2013 Exercise 09 (2022 Fall)

**This exercise notebook will go through the understanding of "Built-in Functions" and "List comprehension" and "Copy"**

- understanding built-in functions
- List comprehension 
- copy values in Python

## Built-in Functions 

Python provides a lot of built-in functions. We now know a framework of function in Python! Let's check some popular built-in functions again.

In [ ]:
x = abs(-3.44)    # 리턴값이 있으니 할당 가능
print(x)

3.44

In [ ]:
my_lst = [True, True, 1, 'a']
x = all(my_lst)
print(x)
my_lst = [False, 0, 'a']  
y = any(my_lst)
print(y)
print(any([False,0]))

True
True
False

In [ ]:
fruits = ('Apple', 'Banana','Kiwi')
x = enumerate(fruits)

print(x)
print(type(x))
print(list(x))

y = enumerate(fruits, start=1)
print(list(y))

for val in fruits:               # 값을 가져오고 싶어
  print(val)

for val in enumerate(fruits):    # index도 같이
  print(val)

for i, val in enumerate(fruits):   # 각각 따로따로
  print(i, val)

for i, val in enumerate(fruits, start=100):
  print(i, val)

<enumerate object at 0x7fd5363d1c80>
<class 'enumerate'>
[(0, 'Apple'), (1, 'Banana'), (2, 'Kiwi')]
[(1, 'Apple'), (2, 'Banana'), (3, 'Kiwi')]
Apple
Banana
Kiwi
(0, 'Apple')
(1, 'Banana')
(2, 'Kiwi')
0 Apple
1 Banana
2 Kiwi
100 Apple
101 Banana
102 Kiwi

In [ ]:
x = input('Enter your name: ')
print('Hi! '+x)

In [ ]:
x = input('Enter employee name, age, and salary separated by space: ')
print(x)

Enter employee name, age, and salary separated by space: lee 18 dongguk
lee 18 dongguk

In [ ]:
name, age, salary = input('Enter employee name, age, and salary separated by space: ').split()
print(f'Employee information: Name {name}, Age {age}, Salary {salary}')
print(f'Type of each input: Name {type(name)}, Age {type(age)}, Salary {type(salary)}')

Enter employee name, age, and salary separated by space: lee 18 dongguk
Employee information: Name lee, Age 18, Salary dongguk
Type of each input: Name <class 'str'>, Age <class 'str'>, Salary <class 'str'>

In [ ]:
input_str = input('Enter numbers of a list separated by space: ')

input_lst = input_str.split()
print('input list: ', input_lst)

for i in range(len(input_lst)):
  input_lst[i] = int(input_lst[i])

print('input list: ', input_lst)

Enter numbers of a list separated by space: 1 2 3 4 5
input list:  ['1', '2', '3', '4', '5']
input list:  [1, 2, 3, 4, 5]

In [ ]:
# ***
n = int(input('Enter the size of the list: '))
print('\n')
input_lst = list(int(num) for num in input('Enter the list elements separated by space: ').split()[:n])

print('input list: ', input_lst)

Enter the size of the list: 5


Enter the list elements separated by space: 1 3 2 5 4
input list:  [1, 3, 2, 5, 4]

Get multiple lines, where each line is taken by using `input()`

In [ ]:
# list to store multi-line input
# press enter Q to exit

data = []
print("Tell me about yourself (enter Q to exit): ")
while True:
    line = input()

    if line == 'Q':
      break
    else:
      data.append(line)

Tell me about yourself (enter Q to exit):
hi everyone
my name is enak
Q

In [ ]:
print(data)

finalText = '\n'.join(data)
print("Final text input")
print(finalText)

['hi everyone', 'my name is enak']
Final text input
hi everyone
my name is enak

In [ ]:
name = input('Enter name: ')
age = input('Enter age: ')
salary = input('Enter salary: ')
company = input('Enter company name: ')

Enter name: a
Enter age: 1
Enter salary: b
Enter company name: c

In [ ]:
print(name, age, salary, company, sep=', ')
print(name, age, salary, company, sep='-')

print(name, end=', ')
print(age, end=', ')
print(salary, end=', ')
print(company)

a, 1, b, c
a-1-b-c
a, 1, b, c

In [ ]:
#range()
#x = range(11)
#x = range(2,11)
x = range(2,11,3)

print(x)

for i in x:
  print(i)

In [ ]:
x = round(3.1415, 3)
y = round(3.1415)
print(x)
print(y)

x = round(-3.1415, 6)
y = round(-3.1415)
print(x)
print(y)

3.142
3
-3.1415
-3

In [ ]:
my_tup = ('c','g','f','q','h','y','a','p','k')
x = sorted(my_tup)
print(x)
y = sorted(my_tup, reverse=True)
z = sorted(my_tup, reverse=False)
print(y)
print(z)

# [].sort() : 리스트 클래스의 메소드(멤버함수). 리스트를 수정. 리턴x(none)
# sorted() : 파이썬 제공 내장함수. 원본은 그대로, 정렬된 리스트를 리턴

['a', 'c', 'f', 'g', 'h', 'k', 'p', 'q', 'y']
['y', 'q', 'p', 'k', 'h', 'g', 'f', 'c', 'a']
['a', 'c', 'f', 'g', 'h', 'k', 'p', 'q', 'y']

In [ ]:
a = zip([10,20,30], ('Apple','Banana','Kiwi'))
print(a)
print(list(a))
a = zip(['a','b','c'], ('Apple','Banana','Kiwi'))
print(a)
print(list(a))

<zip object at 0x7fd53db776e0>
[(10, 'Apple'), (20, 'Banana'), (30, 'Kiwi')]
<zip object at 0x7fd53db92eb0>
[('a', 'Apple'), ('b', 'Banana'), ('c', 'Kiwi')]

In [ ]:
for item in zip([10,20,30], ('Apple','Banana','Kiwi')):
  print(item)

(10, 'Apple')
(20, 'Banana')
(30, 'Kiwi')

In [ ]:
my_tup = ['c','g','f','q','h','y','a','p','k']

for item in zip(range(5), sorted(my_tup)):
  print(item)

# print(list(zip(range(5), sorted(my_tup))))

(0, 'a')
(1, 'c')
(2, 'f')
(3, 'g')
(4, 'h')
[(0, 'a'), (1, 'c'), (2, 'f'), (3, 'g'), (4, 'h')]

## List comprehensions

```
[ expression for item in iterable ]
```
```
[ output parameter | the iterable | condition ]
```

1. Iterating through a string 'human'

In [ ]:
l_list = []

for letter in 'human':
  l_list.append(letter)

print(l_list)

['h', 'u', 'm', 'a', 'n']

In [ ]:
l_list = [ letter for letter in 'human' ]
print(l_list)

['h', 'u', 'm', 'a', 'n']

In [ ]:
l_list = [ letter+'?' for letter in 'human']
print(l_list)

['h?', 'u?', 'm?', 'a?', 'n?']

In [ ]:
lst_1 = [x for x in range(0,10)]
print(lst_1)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

2. Conditionals in list comprehension

In [ ]:
n_list = [ x for x in range(10) if x % 2 == 0 ]
print(n_list)

[0, 2, 4, 6, 8]

In [ ]:
lst_2 = [x for x in range(0,10) if x > 5]
print(lst_2)

[6, 7, 8, 9]

In [ ]:
lst_3 = [x for x in 'Python Programming' if x in ['a','e','i','o','u']]
print(lst_3)

['o', 'o', 'a', 'i']

In [ ]:
lst = []
for i in range(1,30):
  if int(i**0.5) == i**0.5:
    lst.append(i)

print(lst)

[1, 4, 9, 16, 25]

In [ ]:
lst = [i for i in range(1,30) if int(i**0.5) == i**0.5]
print(lst)

3. Nested IF, If-Else with list comprehension

In [ ]:
n_list = [x for x in range(21) if x % 2 == 0 if x % 3 == 0 ]
print(n_list)
n_list = [x for x in range(21) if x % 2 == 0 and x % 3 == 0 ]
print(n_list)

[0, 6, 12, 18]
[0, 6, 12, 18]

In [ ]:
n_list = [(x,'Even') if x % 2 == 0 else (x,'Odd') for x in range(5)]
print(n_list)

[(0, 'Even'), (1, 'Odd'), (2, 'Even'), (3, 'Odd'), (4, 'Even')]

4. Nested loops in list comprehension

In [ ]:
n_list = [[i*j for j in range(1,11)] for i in [2,3,5]]
print(n_list)

[[2, 4, 6, 8, 10, 12, 14, 16, 18, 20], [3, 6, 9, 12, 15, 18, 21, 24, 27, 30], [5, 10, 15, 20, 25, 30, 35, 40, 45, 50]]

In [ ]:
lst = [ (i, j) for i in range(3) for j in range(3)]
print(lst)
# 바로 이어쓰기 가능
# 뒤에가 먼저 증가한다

5. Comprehension for dictionary

In [ ]:
def dict_for(keys, values):
  my_dct = {}
  for i in range(len(keys)):
    my_dct[keys[i]] = values[i]
  return my_dct

Movie = ['Sholay', 'Wanted', 'War']
Actor = ['Amitabh', 'Salman', 'Hritik']
print(dict_for(Movie, Actor))

In [ ]:
def dict_compr(keys, values):
  return {keys[i]: values[i] for i in range(len(keys))}

Movie = ['Sholay', 'Wanted', 'War']
Actor = ['Amitabh', 'Salman', 'Hritik']
print(dict_compr(Movie, Actor))

## Copy in Python

How to copy values in Python? 

1. Use **assignment operator "="**
- values are not copied: both the variable is just referring to the same object

In [ ]:
# copy using an assignment operator

lst_a = [2,5,4,3,6,1]
print(lst_a)

lst_b = lst_a
print(lst_b)

lst_a[0] = 10
print(lst_a)
print(lst_b)

[2, 5, 4, 3, 6, 1]
[2, 5, 4, 3, 6, 1]
[10, 5, 4, 3, 6, 1]
[10, 5, 4, 3, 6, 1]

2. Use **constructor** or **slicing**
- the list is copied

In [ ]:
# copy using constructor, or slicing

lst_a = [2,5,4,3,6,1]
print(lst_a)

lst_b = list(lst_a)
print(lst_b)

lst_c = lst_a[0:3]
print(lst_c)

lst_a[0] = 10
print(lst_a)
print(lst_b)
print(lst_c)

[2, 5, 4, 3, 6, 1]
[2, 5, 4, 3, 6, 1]
[2, 5, 4]
[10, 5, 4, 3, 6, 1]
[2, 5, 4, 3, 6, 1]
[2, 5, 4]

3. Use shallow copy **copy()**
- the list is copied
- but it cannot copy a nested List

In [ ]:
# copy using shallow copy: copy()

from copy import copy

lst_a = [2,5,4,3,6,1]
print(lst_a)

lst_b = copy(lst_a)
print(lst_b)

lst_a[0] = 10
print(lst_a)
print(lst_b)

[2, 5, 4, 3, 6, 1]
[2, 5, 4, 3, 6, 1]
[10, 5, 4, 3, 6, 1]
[2, 5, 4, 3, 6, 1]

In [ ]:
# shallow copy for nested list

from copy import copy

lst_a = [1,[2,3],[4,5]]
print(lst_a)

lst_b = copy(lst_a)
print(lst_b)

lst_a[0] = 10
lst_a[1][0] = 100
print(lst_a)
print(lst_b)

[1, [2, 3], [4, 5]]
[1, [2, 3], [4, 5]]
[10, [100, 3], [4, 5]]
[1, [100, 3], [4, 5]]

In [ ]:
print(id(lst_a))
print(id(lst_b))
print(id(lst_a[1]))
print(id(lst_b[1]))

140553839984720
140553839974352
140553840348528
140553840348528

4. Use deep copy **deepcopy()**
- create a new object and recursively keeps adding copies of the nested elements

In [ ]:
# deep copy for nested list: deepcopy()

from copy import deepcopy

lst_a = [1,[2,3],[4,5]]
print(lst_a)

lst_b = deepcopy(lst_a)
print(lst_b)

lst_a[0] = 10
lst_a[1][0] = 100
print(lst_a)
print(lst_b)

## Exercises

### E-1

Using `print()` function, display the given words, e.g., `'word1'`, `'word2'`, `'word3'`, in the format `'word1**word2**word3`.

In [ ]:
# display four words 'My', 'Name', 'is', 'Kim' in the mentioned format
# your code here

print('My', 'Name', 'is', 'Kim',sep='**')

My**Name**is**Kim

### E-2

Write a function `report_GPA` 
- takes a number of classes as a function argument
- in function: the user can enter each of his classes and scores, after which the program prints out a class list, grade list, and average GPA

Resuls:
```
report_GPA(3)
>>>
Class 1
What was the name of this class? >>> SCS2013
What was your score? >>> 95
Class 2
What was the name of this class? >>> AIX7026
What was your score? >>> 76.3
Class 3
What was the name of this class? >>> AIC2001
What was your score? >>> 88.8
Class list: ['SCS2013', 'AIX7026', 'AIC2001']
Score list: [95.0, 76.3, 88.8]
Overall GPA: 86.7
```

In [ ]:
# your code here:
def report_GPA(num_classes):
  # class and score list
  class_list = []
  score_list = []

  # Using a for loop, take user inputs of name of each class and corresponding score,
  # and add it to class_list and score_list
  for i in range(num_classes):
    class_list.append(input('What was the name of this class? >>> '))
    score_list.append(int(input('What was your score? >>> ')))
  overall_gpa = sum(score_list)/len(score_list)

  print('Class list:', class_list)
  print('Grade list:', score_list)

  # compute the overall gpa as an average of scores
  

  print(f'Overall GPA: {overall_gpa}')

In [ ]:
report_GPA(3)

What was the name of this class? >>> hi
What was your score? >>> 10
What was the name of this class? >>> yes
What was your score? >>> 15
What was the name of this class? >>> enak
What was your score? >>> 20
Class list: ['hi', 'yes', 'enak']
Grade list: [10, 15, 20]
Overall GPA: 15.0

### E-3

Write a list comprehension that prints out the possible results of two coin flips: one result would be `"ht"`. 

Result:
```
['hh', 'ht', 'th', 'tt']
```

In [ ]:
coin = ['h','t']

# your code here:
l = len(coin)
lst = [ coin[i]+coin[j] for i in range(l) for j in range(l)]
print(lst)

['hh', 'ht', 'th', 'tt']

### E-4

Write a function called `pick_vowels` that takes in a string and uses a list comprehension to return all the vowels, i.e., `'a','e','i','o','u'`, in the string.

In [ ]:
vowels = ['a','e','i','o','u']  # vowel은 모음

# your code here:
def pick_vowels(str):
  return [c for c in str if c in vowels]

In [ ]:
# test
print(pick_vowels('hello world! python programming'))

['e', 'o', 'o', 'o', 'o', 'a', 'i']

### E-5

Use a list comprehension to make equivalent results of following nested for loops:

```
n_list = []

for a in [10, 20, 30]:
  for b in [1, 2, 3]:
    n_list.append(a+b)
```

In [ ]:
# using nested for loops
n_list = []

for a in [10, 20, 30]:
  for b in [1, 2, 3]:
    n_list.append(a+b)

print(n_list)

In [ ]:
# your code here:

n_list = [ a + b for a in [10,20,30] for b in [1,2,3]]
print(n_list)

[11, 12, 13, 21, 22, 23, 31, 32, 33]